import type { Metadata } from "next";
import "./globals.css";
import { sansita_swashed, montserrat } from "./font";

export const metadata: Metadata = {
  title: "Shoping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sansita_swashed.variable} ${montserrat.className}`}>
        {children}
      </body>
    </html>
  );
}
