import React from 'react'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next'
import { montserrat, sansita_swashed } from './font'
import './globals.css'
import { Theme } from './theme'
import CsrfComponent from '~/components/csrfComponent'

export const metadata: Metadata = {
  title: 'Brugge',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <CsrfComponent>
      <html lang="en">
        <Theme>
          <body className={`${sansita_swashed.variable} ${montserrat.className}`}>
            <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          </body>
        </Theme>
      </html>
    </CsrfComponent>
  )
}
